services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      # These variables will be available inside the web service container
      # They should match the variables expected by your FastAPI app for DB connection
      DATABASE_URL: postgresql+psycopg://user:password@db:5432/mydatabase
      # Example of existing variable from .env_dev
      API_VERSION: 1.0.0
    depends_on:
      - db
    # Mount the local directory to the container for live reloading during development
    volumes:
      - .:/app
      - /app/.venv
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
